# Generated by Django 5.0.3 on 2024-04-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='defaultprofilepic.jpg', upload_to='profile_pics'),
        ),
    ]
